var TREE_ITEMS = [
	['[MENU PRINCIPAL]', null,
		['Página principal', 'principal.php'],
		['Área do Aluno', 'area_aluno.php'],
		['Alterar senha', 'senha/alterar_senha.php'],
		['Senha dos alunos', 'form_usuario_aluno.php'],
		['Alunos', null,
			['Cadastro', 'aluno/incluir_aluno.php'],
			['Consulta', 'aluno/listar_alunos.php'],
		],
		['Artigos', null,
			['Cadastro', 'artigos/incluir_artigo.php'],
			['Consulta', 'artigos/listar_artigos.php'],
		],
		['Avisos', null,
			['Cadastro', 'avisos/incluir_aviso.php'],
			['Consulta', 'avisos/listar_avisos.php'],
		],
		['Bco Oportunidades', null,
			['Currículos', 'bcoOportunidade/bcoCurriculo/listCurriculos.php'],
			['Empresas',   'bcoOportunidade/bcoEmpresa/listEmpresas.php'],
			['Vagas',      'bcoOportunidade/bcoVaga/listVagas.php'],
		],
		['Cronograma', null,
			['Cadastro', 'cronograma/incluir_cronograma.php'],
			['Consulta', 'cronograma/Lista_Cronograma.php'],
		],
		['Currículo', null,
			['Cadastro', 'curriculos/enviar.php'],
			['Consulta', 'curriculos/listar.php'],
		],
		['Cursos', null,
			['Cadastro', 'cursos/incluir_curso.php'],
			['Consulta', 'cursos/listar_cursos.php'],
		],
		['Depoimentos', null,
			['Aprovar depoimento', 'depoimento/listar_depoimento.php'],
		],
		['Disciplinas', null,
			['Cadastro', 'disciplina/incluir_disciplina.php'],
			['Consulta', 'disciplina/listar_disciplinas.php'],
			['Alterar professor', 'disciplina/alterar_prof_diciplina.php'],
		],
		['Material de Apoio', null,
			['Cadastro', 'exercicio/incluir_exercicio.php'],
			['Consulta', 'exercicio/listar_exercicio.php'],
		],
		['Link', null,
			['Cadastro', 'links/incluir_link.php'],
			['Consulta', 'links/listar_links.php'],
		],
		['Matricula', null,
			['Cadastro', 'matricula/incluir_matricula.php'],
			['Consulta', 'matricula/listar_matriculas.php']
		],
		['Mensagens', null,
			['Para os alunos', 'mensagem/select_aluno.php'],
			['Para as turmas', 'mensagem/select_turma.php'],
			['Para os professores', 'mensagem/select_professor.php'],
		],
		['Notas & Frequências', null,
			['Cadastro', 'notas_frequencias/incluir_notas.php'],
			['Consulta', 'notas_frequencias/consulta/listar_notas_frequencia.php'],
			['Por aluno', 'notas_frequencias/consulta/selCurso.php'],
		],
		['Notícias', null,
			['Cadastro', 'noticia/incluir_noticia.php'],
			['Consulta', 'noticia/listar_noticias.php'],
		],
		['Professores', null,
			['Cadastro', 'professor/incluir_professor.php'],
			['Consulta', 'professor/listar_professores.php'],
		],
		['Relatórios', null,
			['Alunos potenciais', 'relatorios/alunosPotenciais.php'],
			['Boletos emitídos', 'relatorios/boletosEmitidos.php'],
			['Pré-Inscrição', 'relatorios/alunos_cadastrados_pela_web.php'],
			['Newsletter', 'relatorios/newsletterWeb.php'],
			['Histórico Escolar', 'historicoEscolar/formHistoricoEscolar.php'],
		],
		['Turmas', null,
			['Cadastro', 'turmas/incluir_turma.php'],
			['Consulta', 'turmas/consultar_turmas.php'],
		],
		['Usuários Adm.', null,
			['Cadastro', 'usuario_adm/incluir_usuario.php'],
			['Consulta', 'usuario_adm/listar_usuario.php'],
		],
	]
];
